### PR TITLE
try to fix flatpak - attempt #2

### PR DESCRIPTION
**Pull request by pizzadude**
try to fix flatpak - attempt #2

### CODE REVIEW

**Comment by pizzadude** [comment]
bot, build io.github.ec_.Quake3e.OpenArena

**Comment by pizzadude** [comment]
i give up

**Comment by xplshn** [comment]
Does it work? And what did you change and why?

**Comment by pizzadude** [comment]
> Does it work? And what did you change and why?

It doesn't work. The flatpak is still broken.

**Comment by xplshn** [comment]
I will fix it, I thought the Omega engine only added vorbis support back
but it broke lots of things, I'm working on fixing it. SOrry for the inconvenience

**Pull request closed without merging**
